/* tslint:disable */
/* eslint-disable */
/**
 * Road Manager - OpenAPI 3.0
 * Road Manager API
 *
 * The version of the OpenAPI document: 1.0.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { VehicleDTO } from "../models";
import { VehicleDTOFromJSON, VehicleDTOToJSON } from "../models";

export interface RegisterVehicleRequest {
    vehicleDTO: VehicleDTO;
}

/**
 *
 */
export class DriveApi extends runtime.BaseAPI {
    /**
     * Register vehicle
     */
    async registerVehicleRaw(
        requestParameters: RegisterVehicleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<void>> {
        if (
            requestParameters.vehicleDTO === null ||
            requestParameters.vehicleDTO === undefined
        ) {
            throw new runtime.RequiredError(
                "vehicleDTO",
                "Required parameter requestParameters.vehicleDTO was null or undefined when calling registerVehicle."
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        const response = await this.request(
            {
                path: `/drive`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: VehicleDTOToJSON(requestParameters.vehicleDTO),
            },
            initOverrides
        );

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Register vehicle
     */
    async registerVehicle(
        requestParameters: RegisterVehicleRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<void> {
        await this.registerVehicleRaw(requestParameters, initOverrides);
    }
}
