/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { RoadDTO, RoadNetworkDTO } from "../models";
import {
    RoadDTOFromJSON,
    RoadDTOToJSON,
    RoadNetworkDTOFromJSON,
    RoadNetworkDTOToJSON,
} from "../models";

export interface AddOrEditRoadRequest {
    roadDTO: RoadDTO;
}

/**
 *
 */
export class RoadNetworkControllerApi extends runtime.BaseAPI {
    /**
     * Create or update road. When road\'s id == null, system creates new road.Otherwise system gets road from DB with id == road.id and updates all fields.
     */
    async addOrEditRoadRaw(
        requestParameters: AddOrEditRoadRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<RoadDTO>> {
        if (
            requestParameters.roadDTO === null ||
            requestParameters.roadDTO === undefined
        ) {
            throw new runtime.RequiredError(
                "roadDTO",
                "Required parameter requestParameters.roadDTO was null or undefined when calling addOrEditRoad."
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        const response = await this.request(
            {
                path: `/roadNetwork`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: RoadDTOToJSON(requestParameters.roadDTO),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            RoadDTOFromJSON(jsonValue)
        );
    }

    /**
     * Create or update road. When road\'s id == null, system creates new road.Otherwise system gets road from DB with id == road.id and updates all fields.
     */
    async addOrEditRoad(
        roadDTO: RoadDTO,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<RoadDTO> {
        const response = await this.addOrEditRoadRaw(
            { roadDTO: roadDTO },
            initOverrides
        );
        return await response.value();
    }

    /**
     * Get a road network
     */
    async getRoadNetworkRaw(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<RoadNetworkDTO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request(
            {
                path: `/roadNetwork`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) =>
            RoadNetworkDTOFromJSON(jsonValue)
        );
    }

    /**
     * Get a road network
     */
    async getRoadNetwork(
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<RoadNetworkDTO> {
        const response = await this.getRoadNetworkRaw(initOverrides);
        return await response.value();
    }
}
