/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Junction
 */
export interface Junction {
    /**
     *
     * @type {number}
     * @memberof Junction
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof Junction
     */
    name?: string;
    /**
     *
     * @type {number}
     * @memberof Junction
     */
    latitude?: number;
    /**
     *
     * @type {number}
     * @memberof Junction
     */
    longitude?: number;
}

/**
 * Check if a given object implements the Junction interface.
 */
export function instanceOfJunction(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JunctionFromJSON(json: any): Junction {
    return JunctionFromJSONTyped(json, false);
}

export function JunctionFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): Junction {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: !exists(json, "id") ? undefined : json["id"],
        name: !exists(json, "name") ? undefined : json["name"],
        latitude: !exists(json, "latitude") ? undefined : json["latitude"],
        longitude: !exists(json, "longitude") ? undefined : json["longitude"],
    };
}

export function JunctionToJSON(value?: Junction | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        name: value.name,
        latitude: value.latitude,
        longitude: value.longitude,
    };
}
