/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { Passage } from "./Passage";
import {
    PassageFromJSON,
    PassageFromJSONTyped,
    PassageToJSON,
} from "./Passage";

/**
 *
 * @export
 * @interface PaymentDTO
 */
export interface PaymentDTO {
    /**
     *
     * @type {number}
     * @memberof PaymentDTO
     */
    id?: number;
    /**
     *
     * @type {boolean}
     * @memberof PaymentDTO
     */
    paid?: boolean;
    /**
     *
     * @type {number}
     * @memberof PaymentDTO
     */
    price?: number;
    /**
     *
     * @type {Passage}
     * @memberof PaymentDTO
     */
    passage?: Passage;
}

/**
 * Check if a given object implements the PaymentDTO interface.
 */
export function instanceOfPaymentDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaymentDTOFromJSON(json: any): PaymentDTO {
    return PaymentDTOFromJSONTyped(json, false);
}

export function PaymentDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): PaymentDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: !exists(json, "id") ? undefined : json["id"],
        paid: !exists(json, "paid") ? undefined : json["paid"],
        price: !exists(json, "price") ? undefined : json["price"],
        passage: !exists(json, "passage")
            ? undefined
            : PassageFromJSON(json["passage"]),
    };
}

export function PaymentDTOToJSON(value?: PaymentDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        paid: value.paid,
        price: value.price,
        passage: PassageToJSON(value.passage),
    };
}
