/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { RoadDTO } from "./RoadDTO";
import {
    RoadDTOFromJSON,
    RoadDTOFromJSONTyped,
    RoadDTOToJSON,
} from "./RoadDTO";

/**
 *
 * @export
 * @interface RoadNetworkDTO
 */
export interface RoadNetworkDTO {
    /**
     *
     * @type {Array<RoadDTO>}
     * @memberof RoadNetworkDTO
     */
    roadDTOS?: Array<RoadDTO>;
}

/**
 * Check if a given object implements the RoadNetworkDTO interface.
 */
export function instanceOfRoadNetworkDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RoadNetworkDTOFromJSON(json: any): RoadNetworkDTO {
    return RoadNetworkDTOFromJSONTyped(json, false);
}

export function RoadNetworkDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): RoadNetworkDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        roadDTOS: !exists(json, "roadDTOS")
            ? undefined
            : (json["roadDTOS"] as Array<any>).map(RoadDTOFromJSON),
    };
}

export function RoadNetworkDTOToJSON(value?: RoadNetworkDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        roadDTOS:
            value.roadDTOS === undefined
                ? undefined
                : (value.roadDTOS as Array<any>).map(RoadDTOToJSON),
    };
}
