/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SubscriptionTypeDTO
 */
export interface SubscriptionTypeDTO {
    /**
     *
     * @type {number}
     * @memberof SubscriptionTypeDTO
     */
    id?: number;
    /**
     *
     * @type {string}
     * @memberof SubscriptionTypeDTO
     */
    name?: string;
    /**
     *
     * @type {number}
     * @memberof SubscriptionTypeDTO
     */
    period?: number;
    /**
     *
     * @type {number}
     * @memberof SubscriptionTypeDTO
     */
    price?: number;
    /**
     *
     * @type {string}
     * @memberof SubscriptionTypeDTO
     */
    type?: SubscriptionTypeDTOTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum SubscriptionTypeDTOTypeEnum {
    Car = "CAR",
    Truck = "TRUCK",
}

/**
 * Check if a given object implements the SubscriptionTypeDTO interface.
 */
export function instanceOfSubscriptionTypeDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubscriptionTypeDTOFromJSON(json: any): SubscriptionTypeDTO {
    return SubscriptionTypeDTOFromJSONTyped(json, false);
}

export function SubscriptionTypeDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SubscriptionTypeDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        id: !exists(json, "id") ? undefined : json["id"],
        name: !exists(json, "name") ? undefined : json["name"],
        period: !exists(json, "period") ? undefined : json["period"],
        price: !exists(json, "price") ? undefined : json["price"],
        type: !exists(json, "type") ? undefined : json["type"],
    };
}

export function SubscriptionTypeDTOToJSON(
    value?: SubscriptionTypeDTO | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        id: value.id,
        name: value.name,
        period: value.period,
        price: value.price,
        type: value.type,
    };
}
