/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { SubscriptionTypeDTO } from "./SubscriptionTypeDTO";
import {
    SubscriptionTypeDTOFromJSON,
    SubscriptionTypeDTOFromJSONTyped,
    SubscriptionTypeDTOToJSON,
} from "./SubscriptionTypeDTO";

/**
 *
 * @export
 * @interface SubscriptionPaymentDTO
 */
export interface SubscriptionPaymentDTO {
    /**
     *
     * @type {number}
     * @memberof SubscriptionPaymentDTO
     */
    blickNumber?: number;
    /**
     *
     * @type {SubscriptionTypeDTO}
     * @memberof SubscriptionPaymentDTO
     */
    subscriptionType?: SubscriptionTypeDTO;
}

/**
 * Check if a given object implements the SubscriptionPaymentDTO interface.
 */
export function instanceOfSubscriptionPaymentDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SubscriptionPaymentDTOFromJSON(
    json: any
): SubscriptionPaymentDTO {
    return SubscriptionPaymentDTOFromJSONTyped(json, false);
}

export function SubscriptionPaymentDTOFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean
): SubscriptionPaymentDTO {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        blickNumber: !exists(json, "blickNumber")
            ? undefined
            : json["blickNumber"],
        subscriptionType: !exists(json, "subscriptionType")
            ? undefined
            : SubscriptionTypeDTOFromJSON(json["subscriptionType"]),
    };
}

export function SubscriptionPaymentDTOToJSON(
    value?: SubscriptionPaymentDTO | null
): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        blickNumber: value.blickNumber,
        subscriptionType: SubscriptionTypeDTOToJSON(value.subscriptionType),
    };
}
